spring:
  config:
    activate:
      on-profile: dev
  application:
    name: care-external
  redis:
    host: localhost
    port: 6379
    expire: 3000
  api:
    auth:

queryAPIURI: ss
testAPIURI:

server:
  port: 8081
