spring:
  config:
    activate:
      on-profile: dev
  application:
    name: care-dev-env
  redis:
    host: localhost
    port: 6379
    expire: 3000
  api:
    auth:

queryAPIURI: querydevAPIs
testAPIURI:

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

        
